### ISSUE TITLE
GetTextFromS3Async Error

### ISSUE THREAD

**Issue by nrcmkoh** [raol/amazon-sqs-net-extended-client-lib#14]
I am seeing the following message in our logs:

> Failed to get the S3 object which contains the message payload. Message was not received.

This appears to be coming from [here](https://github.com/raol/amazon-sqs-net-extended-client-lib/blob/master/src/Amazon.SQS.ExtendedClient/AmazonSQSExtendedClient.cs#L376). I'd like to see an ErrorCode or something else that might give me more information. 

How can I catch this error to get more information about it? It doesn't catch an exception of type AmazonClientException.

```
try {
  var response = client.ReceiveMessageAsync(request).Result;
} catch (AmazonClientException ex) {
// doesn't enter here
} catch (Exception ex) {
// enters here, but I want to get more info about the error
}
```

**Comment by raol** [comment]
Hi, I'm wrapping the original exception, as you can see from [here](https://github.com/raol/amazon-sqs-net-extended-client-lib/blob/0f48c2620eb7ef89fa09f739de30ceb37d76eeb6/src/Amazon.SQS.ExtendedClient/AmazonSQSExtendedClient.cs#L378)
So to get all details you need to log `InnerException` for the exception you caught.
