### ISSUE TITLE
ChangeMessageVisibilityAsync() Fails for messages from S3

### ISSUE THREAD

**Issue by nrcmkoh** [raol/amazon-sqs-net-extended-client-lib#15]
Hi there, I am getting an exception when I execute this method for messages from S3. It works fine for messages that aren't serialized to S3.

My code looks like this:
```
            try {
                var request = new ChangeMessageVisibilityRequest(queue, receiptHandle, 5);
                var result = sqsClient.ChangeMessageVisibilityAsync(request).Result;
            } catch (MessageNotInflightException ex) {
                _logger.LogError(ex, ex.Message);
                throw;
            } catch (ReceiptHandleIsInvalidException ex) {
                _logger.LogError(ex, ex.Message);
                throw;
            } catch (Exception ex) {
                // Error is getting caught here
                throw;
            }
````

I suspect that the receipt handle is unrecognizable to this method when the message is in S3.

**Comment by raol** [comment]
Thanks. I'll try to look into this in the near future.

**Comment by csheets-omnitracs** [comment]
just wondering if there is an update on this issue? -- I am evaluating the extended client for large SQSS messages and we use ChangeMessageVisibilityAsync method often and so have run into this
