### ISSUE TITLE
Support for .NET 4.0 Client Profile

### ISSUE THREAD

**Issue by kknd4eva** [raol/amazon-sqs-net-extended-client-lib#16]
Hi there, i was wondering if there's any possibility of building this library with support for .NET 4.0 Client Profile. I'm hoping to use the library, but the client machines will only support a maximum of this .NET version. Do you see there being any dependencies that wouldn't allow the library to be re-built against .NET 4.0?

**Comment by raol** [comment]
Sorry, .NET 4.0 is not supported by Microsoft anymore. So I'd like to avoid spending my time backporting this library to 4.0 either.
