### ISSUE TITLE
Unable to install NuGet package Amazon.SQS.ExtendedClient

### ISSUE THREAD

**Issue by gitbitlit** [raol/amazon-sqs-net-extended-client-lib#9]
> Error	 : Could not install package 'Amazon.SQS.ExtendedClient 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by raol** [comment]
@gitbitlit you can use old version which targets old framework.
Install-Package Amazon.SQS.ExtendedClient -Version 0.2.3

**Comment by raol** [comment]
Closing this issue because of existing workaround.

**Comment by raol** [comment]
@gitbitlit I've finally backported the package to the net45. You can use the latest version now.
